### ISSUE TITLE
"no module named filters"?

### ISSUE THREAD

**Issue by srhbutts** [Xpktro/bndr#1]
After installing bndr via pip and trying to run it via powershell in windows 10 with python 3.5.2, i get the following:

`PS C:\Users\me> bndrimg
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python35-32\Scripts\bndrimg-script.py", line 11, in <module>
    load_entry_point('bndr==1.0', 'console_scripts', 'bndrimg')()
  File "c:\users\me\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 565, in load_e
ntry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\me\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_
entry_point
    return ep.load()
  File "c:\users\me\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\me\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2297, in resol
ve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\me\appdata\local\programs\python\python35-32\lib\site-packages\bndr\__init__.py", line 4, in <module>
    from filters import *
ImportError: No module named 'filters'`

**Comment by Xpktro** [comment]
Hello @zoopnarp and thanks for noticing this. I patched the project to support Python 3 so now you can install the latest version from pip and it would work normally :)
